version: '3'

services:

  db:
    image: ynb08/mariadb
    expose:
      - 3306
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - myNetwork

  nginx1:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./default1.conf:/etc/nginx/conf.d/default.conf"
      - "./docker_project_files/:/var/www/html/"
    networks:
      - myNetwork
    depends_on:
      - php1

  nginx2:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - "./default2.conf:/etc/nginx/conf.d/default.conf"
      - "./docker_project_files/:/var/www/html/"
    networks:
      - myNetwork
    depends_on:
      - php2

  php1:
    build: 
      context: .
      dockerfile: php.dockerfile
    expose:
      - 9000
    networks:
      - myNetwork
    depends_on:
      - db

  php2:
    build: 
      context: .
      dockerfile: php.dockerfile
    expose:
      - 9000
    networks:
      - myNetwork
    depends_on:
      - db


volumes:
  database_data:

networks:
  myNetwork:
    driver: bridge